### ISSUE TITLE
RSENSE_HOME setting

### ISSUE THREAD

**Issue by kwerle** [Samsinite/rsense#3]
Let us set RSENSE_HOME in the bundle configuration.

**Comment by kwerle** [comment]
When trying to use rsense:
Exception in thread "main" java.lang.NoClassDefFoundError: org/cx4a/rsense/Main
Caused by: java.lang.ClassNotFoundException: org.cx4a.rsense.Main

Probably because the .jar file is not loaded?

**Comment by Samsinite** [comment]
See your issue above...

**Comment by fancyoung** [comment]
I have the same problem on linux. 

$ bin/rsense server
start: /tmp/rsense-socket (27271)
Exception in thread "main" java.lang.NoClassDefFoundError: org/cx4a/rsense/Main
Caused by: java.lang.ClassNotFoundException: org.cx4a.rsense.Main
    at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
Could not find the main class: org.cx4a.rsense.Main. Program will exit.
singal: CHLD
stop

**Comment by Samsinite** [comment]
The rsense client server wrapper isn't used...  The plugin instead runs through the java interface: "java -cp '.:#{RSense.path}/lib/rsense.jar:#{RSense.path}/lib/antlr-runtime-3.2.jar:#{RSense.path}/lib/jruby.jar' org.cx4a.rsense.Main script '--home=#{RSense.path}' --no-prompt --end-mark=END --config=#{File.dirname(**FILE**)}/../.rsense --progress=1" did you try saving a .rb test file then doing something like "test". then press ctrl+/?

**Comment by fancyoung** [comment]
I have solve my problem. 
the edition I download doesn't have rsense.jar in lib folder.
