### ISSUE TITLE
Could not find the main class: org.cx4a.rsense.Main. Program will exit.

### ISSUE THREAD

**Issue by gacha** [Samsinite/rsense#7]
First error was this:

```
#<Redcar::ApplicationSWT::Treebook:0x1578426>#<Redcar::ApplicationSWT::Treebook:0x1578426>#<Redcar::ApplicationSWT::Treebook:0x1578426>no .rsense file detected, creating .rsense file
/bin/sh: cannot create /home/gatis/Apps/jruby-1.5.0/lib/ruby/gems/1.8/gems/redcar-0.8.1/plugins/rsense/.rsense: Directory nonexistent start time: 12.728
```

Then I created the mssing directory, but then I got next error:

```
#<Redcar::ApplicationSWT::Treebook:0x1885088>#<Redcar::ApplicationSWT::Treebook:0x1885088>#<Redcar::ApplicationSWT::Treebook:0x1885088>start time: 5.737
Couldnt find Setting class for textmate setting: spellchecking
Couldnt find Setting class for textmate setting: spellchecking
indent setting without scope! #<Redcar::Textmate::UnIndentedLinePatternSetting:0xe5f01b @plist="^\\s*$", @scope=nil>
==> RSense: line_str: "". length: 3
==> RSense: line_end_length: 0
==> RSense: prefix:  length: 0
==> RSense: prefix_start_offset: 3
==> RSense: cursor_offset: 33
==> RSense: cursor_line_offset: 3
==> RSense: cursor_line_end_offset: 34
==> RSense: new_line_length: 1
==> RSense: deleted_section: 
==> RSense: command: code-completion '--file=/home/gatis/Code/ruby/bench.rb~' '--location=4:3' '--prefix='
Exception in thread "main" java.lang.NoClassDefFoundError: org/cx4a/rsense/Main
Caused by: java.lang.ClassNotFoundException: org.cx4a.rsense.Main
    at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
Could not find the main class: org.cx4a.rsense.Main. Program will exit.
==> RSense: line_str: "". length: 3
==> RSense: line_end_length: 0
==> RSense: prefix:  length: 0
==> RSense: prefix_start_offset: 3
==> RSense: cursor_offset: 33
==> RSense: cursor_line_offset: 3
==> RSense: cursor_line_end_offset: 34
==> RSense: new_line_length: 1
==> RSense: deleted_section: 
==> RSense: command: code-completion '--file=/home/gatis/Code/ruby/bench.rb~' '--location=4:3' '--prefix='
Error in command Redcar::RSense::CodeCompleteCommand
Errno::EPIPE: Broken pipe - Broken pipe
/home/gatis/.redcar/plugins/rsense/lib/rsense.rb:278:in `get_completions'
/home/gatis/.redcar/plugins/rsense/lib/rsense.rb:241:in `execute'
/home/gatis/Apps/jruby-1.5.0/lib/ruby/gems/1.8/gems/redcar-0.8.1/plugins/application/lib/application/command/executor.rb:29:in `execute'
/home/gatis/Apps/jruby-1.5.0/lib/ruby/gems/1.8/gems/redcar-0.8.1/plugins/application/lib/application/command.rb:83:in `run'
/home/gatis/Apps/jruby-1.5.0/lib/ruby/gems/1.8/gems/redcar-0.8.1/plugins/application/lib/application/menu/item.rb:45:in `selected'
/home/gatis/Apps/jruby-1.5.0/lib/ruby/gems/1.8/gems/redcar-0.8.1/plugins/application_swt/lib/application_swt/menu.rb:133:in `widgetSelected'
/home/gatis/Apps/jruby-1.5.0/lib/ruby/gems/1.8/gems/redcar-0.8.1/plugins/swt/lib/swt/event_loop.rb:13:in `start'
/home/gatis/Apps/jruby-1.5.0/lib/ruby/gems/1.8/gems/redcar-0.8.1/plugins/core/lib/core/gui.rb:39:in `start'
/home/gatis/Apps/jruby-1.5.0/lib/ruby/gems/1.8/gems/redcar-0.8.1/lib/redcar.rb:180:in `pump'
/home/gatis/Apps/jruby-1.5.0/lib/ruby/gems/1.8/gems/redcar-0.8.1/bin/redcar:30
/home/gatis/Apps/jruby-1.5.0/lib/ruby/gems/1.8/gems/redcar-0.8.1/bin/redcar:19:in `load'
```

I have redcar on Ubuntu, then I folowed rsence install steps.

**Comment by gacha** [comment]
Now in 0.9.0 it's working
